### ISSUE TITLE
It doesnt support Latest XCode 

### ISSUE THREAD

**Issue by hemal08ce094** [D-32/WatchPics#5]
Hello Guys as it doesn't support the latest XCode and iOS version, I created another repo that can perform a similar function 

https://github.com/hemal08ce094/InstaFeed

PS: It is very basic and needs major improvement as I created it in spare time. Feel free to raise PR if you can improve it for good. :)

![368x448bb-2](https://user-images.githubusercontent.com/21290914/105622896-9d918b80-5e2e-11eb-9e5f-30223e52cdb0.png)
![368x448bb](https://user-images.githubusercontent.com/21290914/105622897-9f5b4f00-5e2e-11eb-96f1-a8ca9c61590e.png)
![368x448bb-3](https://user-images.githubusercontent.com/21290914/105622898-a1bda900-5e2e-11eb-9f79-6489f8b143de.png)
![368x448bb-1](https://user-images.githubusercontent.com/21290914/105622899-a2563f80-5e2e-11eb-840b-c338d0a3bc4e.png)

**Comment by D-32** [comment]
Looks great! I'll add a link to it in the README :)
